clean:
	rm -f *.submit *.txt *.sub *.log *.out *.err *.metrics readf readf.condor storef storef.condor
copy:
	cp ../mi_binario/readf ../mi_binario/readf.condor ../mi_binario/storef ../mi_binario/storef.condor .
