clean:
	rm -rf *.submit && rm -rf start_dag.condor_dag.*
cleanall:
	rm -rf *.submit && rm -rf start_dag.condor_dag.* && rm -rf datos-adultos-us.csv && rm -rf estadistica.txt && rm -rf header.csv && rm -rf reporte_1.txt && rm -rf reporte_2.txt && rm -rf reporte_3.txt 
